# Generated by Django 3.0.6 on 2020-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to perchased'), ('Sold', 'Currntly out of stock'), ('Restock', 'Item restock in few days')], default='Sold', max_length=150)),
                ('issues', models.CharField(default='No issues', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to perchased'), ('Sold', 'Currntly out of stock'), ('Restock', 'Item restock in few days')], default='Sold', max_length=150)),
                ('issues', models.CharField(default='No issues', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to perchased'), ('Sold', 'Currntly out of stock'), ('Restock', 'Item restock in few days')], default='Sold', max_length=150)),
                ('issues', models.CharField(default='No issues', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
